# TP Python : Pre-processing & Pandas  


##  Un peu de pre-processing avec la team Star Wars  

Importer les 10 premiers personages de star wars depuis l'api du site [swapi](https://swapi.co/) et les ranger dans un dataframe de la√ßon suivante : 
<img src="./StarWarsResult.png">

In [1]:
import requests
import pandas as pd

In [2]:
r = requests.get('https://swapi.co/api/people/1')

In [3]:
data = r.json()

In [30]:
df = pd.DataFrame(columns=data.keys())
columns = list(df)

In [31]:
df

Empty DataFrame
Columns: [name, height, mass, hair_color, skin_color, eye_color, birth_year, gender, homeworld, films, species, vehicles, starships, created, edited, url]
Index: []

In [32]:
r = requests.get('https://swapi.co/api/people/1')
data = r.json()
data

{'name': 'Luke Skywalker',
 'height': '172',
 'mass': '77',
 'hair_color': 'blond',
 'skin_color': 'fair',
 'eye_color': 'blue',
 'birth_year': '19BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.co/api/planets/1/',
 'films': ['https://swapi.co/api/films/2/',
  'https://swapi.co/api/films/6/',
  'https://swapi.co/api/films/3/',
  'https://swapi.co/api/films/1/',
  'https://swapi.co/api/films/7/'],
 'species': ['https://swapi.co/api/species/1/'],
 'vehicles': ['https://swapi.co/api/vehicles/14/',
  'https://swapi.co/api/vehicles/30/'],
 'starships': ['https://swapi.co/api/starships/12/',
  'https://swapi.co/api/starships/22/'],
 'created': '2014-12-09T13:50:51.644000Z',
 'edited': '2014-12-20T21:17:56.891000Z',
 'url': 'https://swapi.co/api/people/1/'}

In [41]:
type(data["films"])

list

In [42]:
for x in range(1, 11):
    r = requests.get('https://swapi.co/api/people/' + str(x))
    data = r.json()
    for key in columns:
        df.loc[x, key] = str(data[key]).strip('[]')
df

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
1,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.co/api/planets/1/,"'https://swapi.co/api/films/2/', 'https://swap...",'https://swapi.co/api/species/1/',"'https://swapi.co/api/vehicles/14/', 'https://...","'https://swapi.co/api/starships/12/', 'https:/...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.co/api/people/1/
2,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.co/api/planets/1/,"'https://swapi.co/api/films/2/', 'https://swap...",'https://swapi.co/api/species/2/',,,2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.co/api/people/2/
3,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.co/api/planets/8/,"'https://swapi.co/api/films/2/', 'https://swap...",'https://swapi.co/api/species/2/',,,2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.co/api/people/3/
4,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.co/api/planets/1/,"'https://swapi.co/api/films/2/', 'https://swap...",'https://swapi.co/api/species/1/',,'https://swapi.co/api/starships/13/',2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.co/api/people/4/
5,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.co/api/planets/2/,"'https://swapi.co/api/films/2/', 'https://swap...",'https://swapi.co/api/species/1/','https://swapi.co/api/vehicles/30/',,2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.co/api/people/5/
6,Owen Lars,178,120,"brown, grey",light,blue,52BBY,male,https://swapi.co/api/planets/1/,"'https://swapi.co/api/films/5/', 'https://swap...",'https://swapi.co/api/species/1/',,,2014-12-10T15:52:14.024000Z,2014-12-20T21:17:50.317000Z,https://swapi.co/api/people/6/
7,Beru Whitesun lars,165,75,brown,light,blue,47BBY,female,https://swapi.co/api/planets/1/,"'https://swapi.co/api/films/5/', 'https://swap...",'https://swapi.co/api/species/1/',,,2014-12-10T15:53:41.121000Z,2014-12-20T21:17:50.319000Z,https://swapi.co/api/people/7/
8,R5-D4,97,32,n/a,"white, red",red,unknown,n/a,https://swapi.co/api/planets/1/,'https://swapi.co/api/films/1/','https://swapi.co/api/species/2/',,,2014-12-10T15:57:50.959000Z,2014-12-20T21:17:50.321000Z,https://swapi.co/api/people/8/
9,Biggs Darklighter,183,84,black,light,brown,24BBY,male,https://swapi.co/api/planets/1/,'https://swapi.co/api/films/1/','https://swapi.co/api/species/1/',,'https://swapi.co/api/starships/12/',2014-12-10T15:59:50.509000Z,2014-12-20T21:17:50.323000Z,https://swapi.co/api/people/9/
10,Obi-Wan Kenobi,182,77,"auburn, white",fair,blue-gray,57BBY,male,https://swapi.co/api/planets/20/,"'https://swapi.co/api/films/2/', 'https://swap...",'https://swapi.co/api/species/1/','https://swapi.co/api/vehicles/38/',"'https://swapi.co/api/starships/48/', 'https:/...",2014-12-10T16:16:29.192000Z,2014-12-20T21:17:50.325000Z,https://swapi.co/api/people/10/

for x in range(1,11):
    r = requests.get('https://swapi.co/api/people/'+str(x))
    data = r.json()
    df = pd.DataFrame({ key:pd.Series(value) for key, value in data.items() })