In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/chipotle.csv')

In [3]:
df.head(10)

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,6,3,1,Side of Chips,NaN,$1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [4]:
df.shape

(4622, 6)

In [5]:
df.columns

Index(['Unnamed: 0', 'order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [6]:
df.groupby('item_name').sum().sort_values('quantity', ascending = False)

                                       Unnamed: 0  order_id  quantity
item_name
Chicken Bowl                              1779909    713926       761
Chicken Burrito                           1238217    497303       591
Chips and Guacamole                       1121773    449959       506
Steak Burrito                              817795    328437       386
Canned Soft Drink                          759990    304753       351
Chips                                      518704    208004       230
Steak Bowl                                 482721    193752       221
Bottled Water                              439354    175944       211
Chips and Fresh Tomato Salsa               250144    100419       130
Canned Soda                                189915     76396       126
Chicken Salad Bowl                         292292    117104       123
Chicken Soft Tacos                         244891     98395       120
Side of Chips                              211009     84769       110
Veggie Burrito                             201321     80962        97
Barbacoa Burrito                           185979     74718        91
Veggie Bowl                                180046     72270        87
Carnitas Bowl                              156599     62742        71
Barbacoa Bowl                              134264     53972        66
Carnitas Burrito                           128611     51652        60
Steak Soft Tacos                           125012     50177        56
6 Pack Soft Drink                          130318     52322        55
Chips and Tomatillo Red Chili Salsa        113585     45556        50
Chicken Crispy Tacos                       118393     47382        50
Chips and Tomatillo Green Chili Salsa      102435     41170        45
Carnitas Soft Tacos                         93766     37673        40
Steak Crispy Tacos                          89408     35818        36
Chips and Tomatillo-Green Chili Salsa       54211     21826        33
Steak Salad Bowl                            73953     29590        31
Nantucket Nectar                            54403     21814        29
Chips and Tomatillo-Red Chili Salsa         45650     18344        25
Barbacoa Soft Tacos                         46454     18725        25
Chips and Roasted Chili Corn Salsa          37152     14999        23
Izze                                        26280     10587        20
Veggie Salad Bowl                           43124     17303        18
Chips and Roasted Chili-Corn Salsa          43554     17462        18
Barbacoa Crispy Tacos                       13825      5613        12
Barbacoa Salad Bowl                         24161      9708        10
Chicken Salad                               26125     10465         9
Carnitas Crispy Tacos                       14567      5868         8
Veggie Soft Tacos                           13737      5520         8
Burrito                                      3734      1550         6
Veggie Salad                                18164      7265         6
Carnitas Salad Bowl                         16710      6693         6
Bowl                                         1118       472         4
Steak Salad                                  5811      2362         4
Salad                                        2829      1150         2
Crispy Tacos                                 1041       434         2
Chips and Mild Fresh Tomato Salsa             674       279         1
Carnitas Salad                               3750      1500         1
Veggie Crispy Tacos                          1653       668         1

In [7]:
df.sum()

Unnamed: 0                                             10679131
order_id                                                4285772
quantity                                                   4972
item_name     Chips and Fresh Tomato SalsaIzzeNantucket Nect...
item_price    $2.39 $3.39 $3.39 $2.39 $16.98 $10.98 $1.69 $1...
dtype: object

In [8]:
df['item_price'] = df['item_price'].str.replace('$','').astype(float)

In [9]:
df.sum()

Unnamed: 0                                             10679131
order_id                                                4285772
quantity                                                   4972
item_name     Chips and Fresh Tomato SalsaIzzeNantucket Nect...
item_price                                              34500.2
dtype: object

In [10]:
revenue_total = (df['quantity']*df['item_price']).sum()
revenue_total

39237.02

In [11]:
df['revenue'] = (df['quantity']*df['item_price'])

In [12]:
moyenne = ((df.groupby('order_id')['revenue'].sum()).mean())

In [13]:
np.round(moyenne, 2)

21.39